# Use an official OpenJDK image as a base image
FROM openjdk:21-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file and the shell script from the current directory to the /app directory in the container
COPY Exporter.jar /app/Exporter.jar
COPY run_exporter.sh /app/run_exporter.sh

# Expose a port if your app is a web application (optional)
# EXPOSE 8080

# Ensure the script is executable
RUN chmod +x /app/run_exporter.sh

# Declare volumes to be mounted from the host
VOLUME ["/app/donalytics", "/app/unzip"]

# Run the shell script
CMD ["sh", "/app/run_exporter.sh"]
